### ISSUE TITLE
cif_core.dic: example data values with standard uncertainties

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#114]
The issue related to the one discussed in #40.

Data item definitions use the ``_description_example.case`` data item to provide example of possible data values. The ``_description_example.case`` data item is defined as having the ``Implied`` container and contents type and as such inherits these properties from the context of the data frame that its instance is used in. This works well in most cases, however, problems arise once the data items that allow standard uncertainties (s.u.) get involved.

For example, the ``_diffrn_standard.decay_percent`` data item is defined as having the ``Measurand`` type purpose (thus requiring standard uncertainties) and provide '**0.5(1)**', '**-1(1)**' and '**0.0(2)**' as data value examples. These are totally legit in regards to the ``_diffrn_standard.decay_percent`` data item definition itself, however, they are not valid in regards to the data item that was used to provide these examples (``_description_example.case``). The ``_description_example.case`` data item inherits the type content (``Real``) and the type container (``Single``) from ``_diffrn_standard.decay_percent``, but is left with its own type purpose (``Key``) and thus is not eligible to contain an s.u. value.

How should situations like these be handled? Is the s.u. eligibility also transferred to the ``_description_example.case`` in some way?

**Comment by jamesrhester** [comment]
I think that the approach is that the example cases are meant for human readers and so we will not try too hard to define the type of values that can appear, that is, I do not think it is worth defining further formal semantics for this particular corner case.

I appreciate that the ultimate reason for being concerned here is when writing machine-verification tools for dictionaries, so I suggest that the `_description_example.case` attribute is special-cased in code so that following the usual checks a further check against the "other" `_type.purpose` is performed. I know that is not very satisfying, but I think it is a pragmatic compromise.

**Comment by vaitkus** [comment]
Acknowledged. Maybe this approach could at least be formalised in a human-readable form of the ``_description_example.case`` data item? For example, the description could be modified in the following way:

_An example case of the defined item. Instances of this data item inherit the container, content and purpose type constraints of the defining item._

**Comment by jamesrhester** [comment]
Agreed.

**Comment by jamesrhester** [comment]
Thank you for the PR.
