### ISSUE TITLE
cif_core: clarification is needed on the data type of the _function.Closest

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#134]
The ``_function.Closest`` definition in the ``cif_core`` dictionary has the ``Matrix(Real,Real,Real)`` content type which is not properly explained by the definition of the ``_type.contents`` data item.
As discussed previously, the ``_type.contents`` does allow to place its enumeration values inside containers, i.e. ``List(Real, Integer, Text)`` describes a value that itself is a list of three elements of the appropriate data types. However, the ``Matrix(Real,Real,Real)`` type is slightly harder to interpret due to the 2D nature of the ``Matrix`` container.

An excerpt from the definition of the ``_function.Closest`` item are placed below for convenience:
```
_type.container                         List
_type.contents                          'Matrix(Real,Real,Real)'
_type.dimension                         '[2]'
loop_
  _method.purpose
  _method.expression
         Evaluation          
;
     Function Closest( v :[Matrix, Real],   # coord vector to be cell translated
                       w :[Matrix, Real]) { # target vector
 
            d  =  v - w
            t  =  Int( Mod( 99.5 + d, 1.0 ) - d )
 
            Closest = List ( v+t, t )
     }
; 

```

As can be seen from the excerpt, the function is expected to return a List of two values of the ``Matrix(Real,Real,Real)``. A look at the function description  makes it clear that the ```Matrix(Real,Real,Real)``` actually refers to a vector of three Real numbers, however, this raises some general questions on the interpretation of the content type:

1) Does a content type consisting of a ``Matrix()`` container and a single list of type enumeration values always implies a vector of fixed size?
2) How would  a content type that defines a ``Matrix()`` of greater dimension (i.e. 3x2) be defined?
I would imagine something along the lines of ``Matrix([Real, Real],[Real, Real],[Real, Real])``?

A slightly more thorough description of such usage would be highly appreciated. It could then be incorporated into the formal definition of the ``_type.contents`` data item in the DDLm core dictionary.

**Comment by jamesrhester** [comment]
The types given in this method, and the <code>Eigen</code> method, appear to be giving dimensions and type for uniform compound elements of a List. I do not believe the proper <code>_type.contents</code> description for the general situation of compound items within compound items has been specified. That said, I think any attempt to come up with a general way of doing this for all possible situations is unnecessary, for 2 reasons:

1.  The compound <code>_type.contents</code> and <code>_type.dimension</code> values are helpers for software systems that are unable to determine this information from the dREL code itself.  Many popular languages can work out variable typing automatically and will ignore compound information.

2.  More fundamentally, all of the awkward compound types that remain (after the removal of synthetic primitive keys) arise because of a wish to return two or more items of information from a function call. These compound types should not correspond to any primitive data name, so we should not waste our mental and programming resources trying to cater to them.  The reason that they "should not" correspond to any primitive data name is because each component will need to be treated differently, and therefore has a separate meaning that can be assigned to a data name.

The only other case of which I am aware is the built-in function "Eigen", which is defined to return the eigenvectors and values together.  The data name to which this result is assigned (<code>_model_site.adp_eigen_system</code>) is never used in dREL, but if it were the value and vector would first have to be separated, just as the results of 'Closest' are separated before performing any operations.  That is, we are exposing an implementation detail where, to save defining functions that are identical except for the returned value, and for computational convenience, final values are combined in a single return statement.

I think the way forward here is not to facilitate the approach of bundling up return values, but rather to define separate functions for each returned value. Especially in the case of dictionary functions, whose purpose is not to be fast, but to be correct. Faster implementations can use the dictionary functions for reference.

**Comment by jamesrhester** [comment]
I will rewrite Closest as two separate functions, and then this problem will go away. Together with replacing the various ``.id`` data names that form lists this should remove any requirement to specify non-uniform element lists.

**Comment by jamesrhester** [comment]
6f611c1 contains the updated Closest function.  As the only difference between the two functions would have been a simple vector addition I have moved this to the only piece of code using it and just simplified the original function.
