### ISSUE TITLE
ddl.dic (cif2-conversion), _enumeration_set.state: are 'Single' & 'Text' intended?

### ISSUE THREAD

**Issue by kkitahara5101** [COMCIFS/cif_core#148]
The values of `_type.container` and `_type.contents` of `_enumeration_set.state` are `Single` and `Text`, respectively. If `_enumeration_set` can be applied only to the items of `Single` and `Text`, then it makes sense. But, I guess `Implied` is better for both.

**Comment by jamesrhester** [comment]
In the case of ``Implied``,  ``_type.container`` and ``_type.contents`` of ``_enumeration_set.state`` would be deduced from the values of these data names for the defined data item. I think this is reasonable, as otherwise it is not clear what the point of  ``_type.container`` and ``_type.contents`` is in the definition in which ``_enumeration_set.state`` is used. If we agree that it is reasonable to change this, I will see what the DDLm group thinks.

**Comment by vaitkus** [comment]
I agree that the `_type.container` could be changed to `Implied` to accommodate data items with more complex data structures.

However, the choice `_type.contents` as `Text` was deliberate and widely discussed in issue #38.
In short, it all boils down to the unambiguity of data value comparison. Comparison of `Text` values is straightforward while comparison of the `Real` type is not that clear cut (i.e. should values "0.5", "0.50", and "5e-1" be considered the same enumeration value?). Since the purpose of an enumerator set is to clearly identify a limited number of well known values, I would say that `Text` is sufficient.

**Comment by kkitahara5101** [comment]
Thanks for the commets.

`Text` is the most generic type in CIF, so it is acceptable unless we do validations of dictionaries. I hope dictionaries can be validated with the same validation software which is also used to CIF data files. For `Real` items, having a non-real value in `_enumeration.set.state` should be invalid. To achieve this behaviour automatically, the type of `_enumeration_set.sate` must match the type of the associated data item.

The problem pointed out by @vaitkus is not limited to the problem of `_type.contents` of `_enumeration_set.state` but rather the definition of equality between the data values. This problem is related to all the validation processes. I think we should keep the `_type.contents` as `Text` for now, and we may move to  `Implied` if we can solve the comparison issue.

Regarding the comparison issue, I show another difficult example here just to remind (I guess we should raise an another 'Issue'). CIF has `Measurand` items. For them, I guess, e.g. if the valid value and its uncertainty are given as `0.150(10)` (through `Evaluation` method for example), then the value `0.145` is valid, `0.135` is invalid (maybe Alert C?), `0.125` is invalid (maybe Alert B?), etc.

**Comment by jamesrhester** [comment]
I think this issue has been resolved (leave as ``Text``). @kkitahara5101 may wish to raise a new issue regarding comparisons.

**Comment by kkitahara5101** [comment]
Thanks for closing the issue, @jamesrhester.
Unfortunately, I do not have much time for this project at the moment. I will try to keep looking discussions. And I may raise a new issue regarding comparisons in future.
