### ISSUE TITLE
Change all List-type .id values to strings

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/cif_core#149]
A number of categories in cif_core define ".id" datanames that are specified to be Lists (e.g. _model_site.id). There is no reason for these to be lists, as these datanames are supposed to be opaque identifiers with no accessible internal structure. I propose changing them all to simple strings formed by concatenating the list elements.

As they are opaque identifiers, there is less reason to be concerned about this change breaking any software, however, if it would be problematic please comment.

**Comment by kkitahara5101** [comment]
I am trying to develop a CIF-DDLm software in Javascript. Category keys of 'List' type are much difficult to treat than strings. If all the category keys (assigned in _category.key_id) are changed to strings, it is really great.

**Comment by vaitkus** [comment]
One drawback of concatenation is the possible loss of identifier uniqueness. For example, lists ('Fe55', '1') and ('Fe5', '51') both produce the same string 'Fe551' and as such are no longer unique. Keeping the values as separate lists does retain the uniqueness.

I imagine that those id values are not generally intended to appear in the CIF files themselves in either form (list or the concatenated string) since they duplicate the information that should already be presented in other fields (`_model_site.label` and `_model_site.symop` in the case of `_model_site.id`). As such, if the id data items are only intended to function as artificial primary keys, that is, uniquely identify each data row without requiring the uniqueness of the data list items, than there is no need for concatenated values as simple integers suffice as identifiers (i.e. in a fashion similar to the `_space_group_symop.id` data item).

That said, in our validation software we do concatenate these values to produce a key while checking the uniqueness constraint. The above mentioned loss-of-uniqueness problem is averted by separating the list elements with a symbol that is not allowed in CIF files and as such is guaranteed not to appear as part of the values (i.e. the ASCII record separator symbol '&#030;'). This approach has proven useful in detecting ambiguities in the COD CIF files such as two identical atom pairs declared as having different interatomic distances. As such, it would be a shame to remove id lists without providing an alternative way of specifying composite unique keys.

**Comment by kkitahara5101** [comment]
The problem pointed out by @vaitkus seems critical. Now I think, the data items should be kept as ''List'. Each implementation may choose to convert the composite keys into strings under the hood.

By the way, why `_model_site.id` has the following definition (nested list)?
https://github.com/COMCIFS/cif_core/blob/1ac8dfa2616d478854b453e9cefc6640f8d802e6/cif_core.dic#L13580-L13582
From the dREL expression `_model_site.id =   List ( m.label, m.symop )`, I think the type should be 
```
    _type.container              List
    _type.contents               "Code,Symop"
    _type.dimension              '[2]'
```

**Comment by jamesrhester** [comment]
> I am trying to develop a CIF-DDLm software in Javascript. Category keys of 'List' type are much difficult to treat than strings. If all the category keys (assigned in _category.key_id) are changed to strings, it is really great.

I am also running into this - this type of data value immensely complicates dREL and the only use is for these type of synthetic ID values.

**Comment by jamesrhester** [comment]
> That said, in our validation software we do concatenate these values to produce a key while checking the uniqueness constraint. The above mentioned loss-of-uniqueness problem is averted by separating the list elements with a symbol that is not allowed in CIF files and as such is guaranteed not to appear as part of the values (i.e. the ASCII record separator symbol '�'). This approach has proven useful in detecting ambiguities in the COD CIF files such as two identical atom pairs declared as having different interatomic distances. As such, it would be a shame to remove id lists without providing an alternative way of specifying composite unique keys.

Isn't it possible to simply change the dREL to generate the composite key as a concatenation with a unicode character, as @vaitkus has done?  As @kkitahara5101 says, heterogeneous lists are complex to code in dREL and specify in DDLm, and are only used in this one place, and for no particular reason beyond trying to generate a unique, opaque key.  For example, we could make the current dREL a "Definition" method for _enumeration.default, and then the .id data name would only be generated (as a string) if nothing else was provided.  Would that suit @vaitkus ?

> I imagine that those id values are not generally intended to appear in the CIF files themselves in either form (list or the concatenated string) since they duplicate the information that should already be presented in other fields (`_model_site.label` and `_model_site.symop` in the case of `_model_site.id`).

They are used as an intermediate generated value, but at the same time they are allowed to appear in CIF2 files if they are defined in the dictionary, and currently must be lists.  Using a list is pointlessly complex, as they are simply supposed to function as a unique opaque key.

**Comment by jamesrhester** [comment]
> From the dREL expression `_model_site.id = List ( m.label, m.symop )`, I think the type should be
> ```
>     _type.container              List
>     _type.contents               "Code,Symop"
>     _type.dimension              '[2]'
> ```

I think @kkitahara5101 is correct. If we decide to leave these datanames as lists, then we should fix this.

**Comment by vaitkus** [comment]
> Isn't it possible to simply change the dREL to generate the composite key as a concatenation with a unicode character, as @vaitkus has done? As @kkitahara5101 says, heterogeneous lists are complex to code in dREL and specify in DDLm, and are only used in this one place, and for no particular reason beyond trying to generate a unique, opaque key. For example, we could make the current dREL a "Definition" method for _enumeration.default, and then the .id data name would only be generated (as a string) if nothing else was provided. Would that suit @vaitkus ?

@jamesrhester I apologise since it seems I have slightly misunderstood the issue. When checking for composite key uniqueness our code retrieves the key data names from the category definition and not the id data item definition (e.g. from the ``_category_key.name`` data item loop in the ``MODEL_SITE`` definition save frame vs. the dREL in ``_model_site.id`` data item). Would it be possible to only simplify the id data item (i.e. as a concatenated string), but retain  the category ``_category_key.name`` values for those willing to construct the unique key on their own?

As for the simplification of the id values, are there any advantages of using a concatenated string instead of an integer identifier?

**Comment by kkitahara5101** [comment]
@jamesrhester
I know [the original code](https://github.com/COMCIFS/JsCifBrowser), but I have not read the detail of this code. I'm still doing small 'experiments' to understand the whole idea of CIF-DDLm. After that, I will explore the detail of the original code. I usually use Apache 2.0 for my code, but if another is useful in this field, then I can change the license.

@vaitkus 
Thanks for the PR. I have not noticed this.

**Comment by jamesrhester** [comment]
Sorry for my disappearance from this discussion, blame the European summer conference/school cycle.

> Would it be possible to only simplify the id data item (i.e. as a concatenated string), but retain the category _category_key.name values for those willing to construct the unique key on their own?
> 
> As for the simplification of the id values, are there any advantages of using a concatenated string instead of an integer identifier?

@vaitkus I am glad that you use ``_category_key.name``, this is the proper use of keys and this attribute should always be present in loop categories. We are not discussing changing this at all. So I think we now all agree that we can change the .id values to Text type, and do not even need to specify any particular default structure for the .id values.  Assuming that this is the case, I have added the 'janitorial' tag to this issue. @vaitkus - I think this means #133 is out of date?

**Comment by vaitkus** [comment]
@jamesrhester I also happy that we came to a consensus. Sorry for my initial misunderstanding. PR #133 was indeed no longer relevant so I have closed it.

I am not opposing the decision nor am I trying to needlessly prolong the discussion, but I would like to spell out some of my final thoughts on the issue that do not necessarily require a response. The decision to use concatenated strings instead of simple integer values as the opaque identifiers has its advantages as well as its drawbacks. On the one hand, the identifier can be generated context-free from the values of a single data packet and as such is not affected by the position of the packet in the looped list (+). On the other hand, the algorithm of generating the identifier is slightly more complex since things like the concatenation character, potentially missing or undefined values, etc. need to be taken into account (-). For comparison, the ``_space_group_symop.id`` data item is a good example of an opaque identifier that has an integer value as well as a snippet of dREL code used to evaluate it.

The "janitorial" label seems appropriate, however, the changes needed are a bit complex. I would be glad to contribute, but it is not entirely clear what modifications should be applied to the dREL (i.e. what concatenation character should be used, how undefined values should be treated, etc.). Maybe the key construction logic could be encompassed in a specialised function that accepts a list of data names that should be used in the key construction? Some kind of a dREL example would be extremely useful.

**Comment by jamesrhester** [comment]
I do not think that we need to specify any particular internal structure for ``_model_site.id`` and any similar identifiers. It is simply guaranteed to be a unique value for every row, and may be generated however the CIF writer would like. Therefore, it is sufficient to change its ``_type.contents`` to 'Text' and ``_type.container`` to 'Single', removing any other ``_type`` information that is relevant only for arrays.

**Comment by jamesrhester** [comment]
a14c7fa contains this (long awaited?) update. ``_type.contents`` and ``_type.purpose`` have been changed. Synthetic key construction instructions have been removed. These keys are not used elsewhere in the dREL at all following a previous update, so any internal structure is not relevant. I am inclined to remove them altogether, but that is a discussion for the future. Please check this commit and comment here.

**Comment by vaitkus** [comment]
The `_geom_contact.id` data item definition still contains an evaluation dREL code snippet that should probably be removed. The description text for the same item also contains a typo (`A identifier` -> `An identifier`).

**Comment by jamesrhester** [comment]
Thanks for checking. 46de1f2 should be correct now...

**Comment by vaitkus** [comment]
Great, thank you for the changes.
