### ISSUE TITLE
New dataname _diffrn_measurement_specimen_adhesive

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/cif_core#161]
A suggestion has been received for a new CIF data item _diffrn_measurement_specimen_adhesive

The suggestion can be reviewed [here](https://www.iucr.org/resources/cif/dictionaries/new-item/cif_core/_diffrn_measurement_specimen_adhesive)

**Comment by jamesrhester** [comment]
A draft definition (missing all of the housekeeping items) has been provided to the core DMG.


```save_diffrn_measurement.specimen_adhesive_type
_definition.id     '_diffrn_measurement.specimen_adhesive_type'
_description.text
;
The type of the adhesive material used to attach the sample to a sample holder.
;
loop_
_enumerated_set.case
_enumerated_set.detail
Epoxy            "An epoxy glue"
Oil                  "A viscous oil"
Frozen_Liquid  "A frozen liquid, not water or oil"
Magnet          "Sample is held in place by magnetic field"
Clay               "Modelling clay"
.                     "No adhesive used"
Ice                 "The specimen is frozen in place using water ice"

save_

save_diffrn_measurement.specimen_adhesive_details
_definition.id     '_diffrn_measurement.specimen_adhesive_details'
_description.text
;
A description of the method of attachment of the sample to the sample holder. The general method of attachment
should be described using _diffrn_measurement.specimen_adhesive_type
;
loop_
_description_example.case
"UHU Super Glue ultrafast gel"
"Flourinert"
"Plasticine"
"Sample was held tightly by a custom aluminium wire framework attached to the sample holder"

save_
```

**Comment by vaitkus** [comment]
Several suggestions:
1. Since "Magnet" is included as one of the available values, the entire definition seems to encompass more than just adhesives. Maybe it would be worthwhile to think of a more encompassing name (i.e. specimen_support_type) and update the human-readable definition appropriately (magnet is not an adhesive material)?  
2. Maybe the '**.**' value could be replaced with a more readable value "**none**"? The CIF_CORE dictionary seems to use both approaches (with more definitions using the '.' notation), however, the '.' is a bit obscure for people not familiar with the CIF syntax. Also, see my ramblings below about why the usage of '.' as an enumeration value seems incorrect. [1]
3. Enumeration values in the CIF_CORE dictionary tend not to use upper-case letters when referring to common nouns. Maybe these values could also be lowercased?
4. Data names `_enumerated_set.case` and `_enumerated_set.detail` should be replaced by `_enumeration_set.state` and `_enumeration_set.detail` in order to be valid against the DDLm reference dictionary.

[1] On a more philosophical note, the data item definition itself becomes ambiguous when the '.' is used as one of the enumeration values. Technically the unquoted '.' symbol states that the enumeration value itself is inapplicable in the context of the definition and not that "if we encounter an inapplicable value in a CIF file, it should be interpreted as X".

**Comment by jamesrhester** [comment]
1. Perhaps 'attachment' as in `specimen_attachment_details` would be better?
2. I agree that `None` would be better
3. If we say that the type is `Code` the matching should be caseless
4. Indeed.

I agree with the philosophical point too.

**Comment by jamesrhester** [comment]
So here's an updated definition:

```save_diffrn_measurement.specimen_attachment_type
_definition.id     '_diffrn_measurement.specimen_attachment_type'
_description.text
;
The way in which the sample is attached to the sample holder, including the type of adhesive material used if relevant. If
the attachment method is not included in the list below, 'Other' should be chosen and details provided in
_diffrn_measurement.specimen_attachment_special_details.
;
_type.contents       Code
loop_
_enumerated_set.case
_enumerated_set.detail
epoxy            "An epoxy glue"
oil                  "A viscous oil"
frozen_liquid  "A frozen liquid, not water or oil"
magnet          "Sample is held in place by magnetic field"
clay               "Modelling clay"
other             "A method not listed here"
ice                 "The specimen is frozen in place using water ice"

save_

save_diffrn_measurement.specimen_attachment_details
_definition.id     '_diffrn_measurement.specimen_attachment_details'
_description.text
;
A description of the method of attachment of the sample to the sample holder. The general method of attachment
should be described using _diffrn_measurement.specimen_attachment_type
;
loop_
_description_example.case
"UHU Super Glue ultrafast gel"
"Fluorinert"
"Plasticine"
"Sample was held tightly by a custom aluminium wire framework attached to the sample holder"

save_
```

**Comment by jamesrhester** [comment]
Feedback from core DMG leads to the following improved definition:

```_definition.id     '_diffrn_measurement.specimen_attachment_type'
_description.text
;
The way in which the sample is attached to the sample holder, including the type of adhesive material used if relevant. If
the attachment method is not included in the list below, 'Other' should be chosen and details provided in
_diffrn_measurement.specimen_attachment_details.
;
_type.contents       Code
loop_
_enumerated_set.case
_enumerated_set.detail
epoxy            "An epoxy glue"
oil                  "An oil"
grease           "A type of grease, for example hydrocarbon or silicone grease"
frozen_liquid  "A frozen liquid, not water or oil"
other             "A method not listed here"
ice                 "The specimen is frozen in place using water ice"
mechanical   "The specimen is held in place by mechanical forces, e.g. capillary or pressure cell"

save_

save_diffrn_measurement.specimen_attachment_details
_definition.id     '_diffrn_measurement.specimen_attachment_details'
_description.text
;
A description of the method of attachment of the sample to the sample holder. The general method of attachment
should be described using _diffrn_measurement.specimen_attachment_type
;
loop_
_description_example.case
"UHU Super Glue ultrafast gel"
"Fluorinert"
"Plasticine"
"Sample was held tightly by a custom aluminium wire framework attached to the sample holder"

save_```

**Comment by jamesrhester** [comment]
Added in commit c70b1e8 after approval by core DMG. `diffrn_measurement.specimen_attachment_details` was not added as the preexisting `specimen_support` was suitable for this purpose.
