### ISSUE TITLE
cif_core.dic: DIFFRN_RADIATION is described as potentially looped, but is actually a set

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#168]
The definition of the `DIFFRN_RADIATION` category states that:
```
Items may be looped to identify and assign weights to distinct wavelength
components from a polychromatic beam.
```

However, the category is formally described as a `Set` category.

The category description is also identical to the description of the `DIFFRN_RADIATION_WAVELENGTH` category and differs from the one provided in the `DDL1` version of the dictionary:
```
Data items in the DIFFRN_RADIATION category describe the radiation used in measuring
the diffraction intensities, its collimation and monochromatization before the sample.

Post-sample treatment of the beam is described by data items in
the DIFFRN_DETECTOR category.
```

There are about ~800 entries in the COD that contain looped instances of data items from the `DIFFRN_RADIATION` category. In most of these cases, the `diffrn_radiation_type` item is looped with other items from the  `DIFFRN_RADIATION_WAVELENGTH` category. For example, COD entry [2311995](https://www.crystallography.net/cod/2311995.html):
```
loop_
_diffrn_radiation_wavelength
_diffrn_radiation_wavelength_wt
_diffrn_radiation_type
_diffrn_radiation_wavelength_id
0.709237 1.000 K\a~1~ 1
0.713647 0.500 K\a~2~ 2
```

However, in a few select cases more than one item from the `DIFFRN_RADIATION` is looped, i.e.
COD entry [4002662](https://www.crystallography.net/cod/4002662.html):
```
loop_
_diffrn_radiation_type
_diffrn_radiation_probe
_diffrn_radiation_monochromator
_diffrn_radiation_filter_edge
_diffrn_radiation_xray_symbol
_diffrn_radiation_wavelength
_diffrn_radiation_wavelength_wt
'Cu K\a' x-ray 'Ni filter' 1.4879 'Cu K-L~3~' 1.540596 0.6681294
'Cu K\a' x-ray 'Ni filter' 1.4879 'Cu K-L~2~' 1.544493 0.3308458
```

As mentioned, there aren't that many instances of such loopness, however, the provided examples are from recent publications (years 2018, 2016). Maybe the `DIFFRN_RADIATION` category could be formally declared as looped and, in this way, allow items from the `DIFFRN_RADIATION_WAVELENGTH` child looped category to be stored in the same loop (as is done with the `ATOM_SITE` and `ATOM_SITE_ANISO` categories)?

**Comment by jamesrhester** [comment]
The immediate problem seems to be that ``diffrn_radiation.type`` should *not* be in DIFFRN_RADITION(DR), but DIFFRN_RADIATION_WAVELENGTH(DRW).  None of the other members of DR would need looping normally.  So the ideal solution would be to simply change the category of ``diffrn_radiation.type`` to DRW.  Of course this will invalidate the few COD entries that loop more than one item from DR but would make the 800 or so others conformant (I think?).  How many other entries would be invalidated because they have ``diffrn_radiation_type`` outside a loop over DRW?

One complication with making DR completely looped is that the dREL method for the form factor calculation (quite reasonably) assumes a single, defined value for ``diffrn_radiation.probe``. This value is then used to calculate appropriate structure factors [I speculate that the original authors wanted DR to be looped, but then realised that the dREL would not work and forgot to fix the description.]

A similar complication not solved by the suggested fix in the first paragraph is that ``atom_type_scat.dispersion_imag`` assumes that ``diffrn_radiation.type`` is a single value which is then used to get the dispersion values from tables for Cu and Mo.  This is really a hack as it is not extensible to synchrotrons.  We can change this dREL to use the weighted wavelength value to look up tables (rather than using type), which would allow the fix in the first paragraph to work.

Before exploring other solutions further, can @vaitkus provide some information on how many COD entries would be invalidated by moving ``diffraction_radiation.type`` into the ``diffrn_radiation_wavelength`` category?

**Comment by vaitkus** [comment]
There are about 230 entries that would become invalid. Details are provided below. 

As of COD revision 249225, about 1400 entries contain a `DIFFRN_RADIATION_WAVELENGTH` loop. Out of those 1400, only about 230 entries contain an unlooped instance of the  `_diffrn_radiation_type` data item and contain more than one row in the `DIFFRN_RADIATION_WAVELENGTH` category loop.

**Comment by jamesrhester** [comment]
I guess the unfortunate thing about moving ``diffrn_radiation_type`` to ``diffrn_radiation_wavelength`` is that the CIF files that are being produced strictly according to the standard (those 230) would now be told that they are doing it incorrectly, in order to satisfy the 800 or so rule breakers. I don't think that is a good precedent to set.

So probably the best solution is to define a new dataname ``_diffrn_radiation_wavelength.type`` and deprecate the previous one. I will put this to the coreDMG but also feel free to comment here as well.

**Comment by vaitkus** [comment]
I fully agree that the number of affected entries is extremely small and as such should generally not require modifications to the dictionary. The main intent of the original issue was to draw attention to the the fact that the `DIFFRN_RADIATION` category description seemed slightly incorrect.

The provided arguments make it clear that making the  `DIFFRN_RADIATION` category a looped one is not a viable approach. I though of of it as a solution that would not break any of the existing files and allow to describe a greater variety of situations, but it is a great thing that @jamesrhester  was quick to point out all of the problems I have missed.

The proposed approach to add a new item and deprecate the old one seems perfectly reasonable,
although slightly more intrusive. I lack the expertise to judge if the trend outlined by the 800 entries is a sufficient reason to carry out these changes. However,  if these changes are indeed applied, I would suggest that the rest of the items from the `DIFFRN_RADIATION` category should be checked for eligibility to be modified in a similar manner. What I mean, is that the `_diffrn_radiation.xray_symbol` data item is closely related to the `_diffrn_radiation.type` item and having them in different categories could lead to some contradicting data.

**Comment by jamesrhester** [comment]
I agree that ``_diffrn_radiation.xray_symbol`` should also be moved, and have included it in the CoreDMG post.

**Comment by jamesrhester** [comment]
There were no objections from core DMG, so now the core dictionary can be updated to move the two data names into the `diffrn_radiation_wavelength` category.
