### ISSUE TITLE
_type.dimension definition and its usage in DDL_DIC v3.11.10 do not match

### ISSUE THREAD

**Issue by merkys** [COMCIFS/cif_core#18]
``_type.dimension`` is defined as a single value (``_type.container    Single``) and is described as ``text string within bounding square brackets`` in [DDL_DIC v3.11.10](../blob/cif2-conversion/ddl.dic). However, values of ``_type.dimension`` seem to be lists exclusively. Which usage is correct?

**Comment by jamesrhester** [comment]
The intention was that _type.dimension can be used to describe heterogenous nested items, so that a string of the form '[5[2,3],6]' would be used to describe 5 lists of 2x3 lists, repeated 6 times.  Such a format string is not a CIF2 list, but a single string, so the dictionary is correct. Any use of _type.dimension in the core dictionaries should be enclosed in string delimiters.

The presence of such complex datavalue structures came about because of the original approach to 'id' datanames, in which category key values were bundled into a single compound datavalue that could be unpacked into its constituents as needed.  This led to some complex heterogenous structures.  As these 'id' datanames are no longer needed, there is no immediate demand for fancy list dimension specifications.

More philosophically, any heterogeneous list wll almost by definition require that its separate parts are treated differently, which implies that the separate parts have different meanings, requiring different datanames.  If this is true, then no heterogeous lists ever need to be defined.  The closest thing in the current dictionary to a heterogenous list is  [_model_site.adp_eigensystem](http://comcifs.github.io/cif_core.dic.html#_model_site_adp_eigen_system), which ideally would be a list of [eigenval, eigenvector], but even in this case each list entry is the same, giving a dimension of 4.

I suggest that we consider simplifying the _type.dimension specification to being a simple list, but that we hold off on this decision until the remaining dictionaries (particularly the modulated structures dictionary) are converted to DDLm, to make absolutely sure that there are no places that a more complex _type.dimension is allowed.

**Comment by merkys** [comment]
@jamesrhester, thank you for a detailed answer. If I understand correctly, the description in ``save_type.dimension`` block is used as of now. However, I am worried that DDL_DIC v3.11.10 does not validate against itself as of now, as all values of ``_type.dimension`` are given as lists instead of text strings, for example:
```
save_dictionary_valid.application
...
    _type.dimension              [2]
```
while it should be given as
```
save_dictionary_valid.application
...
    _type.dimension              '[2]'
```

**Comment by jamesrhester** [comment]
I have corrected the values of _type.dimension as @merkys suggests.

**Comment by merkys** [comment]
Thanks for a prompt fix, @jamesrhester!
