### ISSUE TITLE
 cif_core.cif2.dic (cif2-conversion): _symmetry and _space_group data items should not be treated as aliases in some cases

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#20]
In the DDL1 ``cif_core`` dictionary the ``_symmetry_*`` data items were deprecated and marked as replaced by the ``_space_group_* `` data items. In some instances, however, the data name was not the only thing changed, for example:

1) ``_symmetry_cell_setting`` and ``_space_group_crystal_system`` are both described as enumerators, but the latter does not have the ``rhombohedral`` value listed based on the fact that ``trigonal`` value encompasses it;
2) ``_symmetry_space_group_name_H-M`` was declared as a strictly unlooped value whereas ``_space_group_name_H-M_alt`` was declared as being either looped or unlooped.

As a result, these data names should probably not be marked as aliases. Or does the concept of 'alias' in the DDLm encompasses these differences? Maybe a mechanism of linking deprecated data items to their newer alternatives could be introduced into the DDLm as well?

I add the relevant excerpt from the cif_core DDLm below:
```
save__symmetry.cell_setting

_definition.id                          '_symmetry.cell_setting'
loop_
  _alias.definition_id
         '_symmetry.cell_setting'      
         '_symmetry_cell_setting'      
         '_space_group_crystal_system' 
...
save_

save__space_group.crystal_system

_definition.id                          '_space_group.crystal_system'
loop_
  _alias.definition_id
         '_space_group.crystal_system' 
...
save_
```

**Comment by jamesrhester** [comment]
(1) _space_group_name-H-M_alt should never have been looped in the original DDL1 dictionaries, and as far as we can tell, never was (see also comment on #22 ).  So there is a clarification of the DDL1 definition - if you like, we are saying retrospectively that any looped use of the DDL1 dataname was incorrect.

(2) I believe that the list of alternatives for space_group.crystal_system is meant to be a correct listing of crystal systems, implying that 'rhombohedral' should never have been included in _symmetry_cell_setting. In this case this is likewise a retrospective correction to the original definition. I am not sure how often "rhombohedral" was used in this case so I will consult with the core CIF group to see what they think.

**Comment by jamesrhester** [comment]
Upon consultation of International Tables for Crystallography, Vol G, p 254-55, it is clear that 'trigonal' was mistakenly included in `_symmetry_cell_setting`, which was consequently deprecated and a new dataname `_space_group_crystal_system` defined. The latter does list `_symmetry_cell_setting` as an alternate. [This message](http://www.iucr.org/__data/iucr/lists/cif-developers/msg00170.html) appears to be the only record of this change.
_symmetry_cell_setting is still very widely used, I counted 874 occurrences in the COD as of May last year.  We must maintain some reference to this dataname in order to interpret these datafiles.  Therefore I suggest that we add a new definition to the DDLm core_CIF for this dataname, with a definition that indicates that it is deprecated.  I will liaise with the core CIF dictionary management group to get this to happen.

**Comment by jamesrhester** [comment]
This issue has been resolved by (i) removing the alias between `space_group.crystal_system` and `symmetry.cell_setting` (ii) defining a new DDLm attribute for deprecation (`definition.replaced_by`) (iii) returning a `symmetry.cell_setting` definition to cif_core and deprecating it using the new attribute. cif_core and ddl.dic are now updated

**Comment by vaitkus** [comment]
Thank you for the correction.
