### ISSUE TITLE
Unit of measurement of the _refine_diff.density_* data items

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#205]
Units of measurement of the `_refine_diff.density_min`, `_refine_diff.density_min_su`, `_refine_diff.density_max`, `_refine_diff.density_max_su`, `_refine_diff.density_rms` and `_refine_diff.density_rms_su` data items are currently assigned using the following definition method:
```
     If (_diffrn_radiation.probe == "neutron")  _units.code =  "femtometres"
Else If (_diffrn_radiation.probe == "electron") _units.code =  "volts"
Else                                            _units.code =  "electrons"
```
Based on the DDL1 version of the `CIF_CORE` dictionary the `electrons` unit should most likely be `electrons_per_angstrom_cubed`, however, I am unsure if the same can be extrapolated to `femtometres` and `volts`. For example, `femtometres_per_angstrom_cubed` would look extremely strange as a unit of density given that both the `femtometers` and `angstroms` are units of length. What would be the proper units (if any) for the rest of the radiation probes?

**Comment by jamesrhester** [comment]
X-rays and electrons both produce electrons per angstrom cubed. Neutron scattering uses "scattering length" instead of "electrons". So the density becomes scattering length in femtometres per cubic angstrom, and the lengths on the top and bottom can cancel out to get "angstrom^-2". Typically (e.g.  https://www.ncnr.nist.gov/resources/activation/) the units are then 10^-6/A^2, which is just the same as femtometres/cubic angstrom. So I think it is OK to have femtometres/cubic angstrom as this makes the 10^-6 scaling explicit.

**Comment by rowlesmr** [comment]
> What units should be applied to gamma radiation (`gamma` is one of enumeration values given for `_diffrn_radiation.probe`)?

I would guess that `gamma` would be the same units as `x-ray`; they're both photons.

**Comment by jamesrhester** [comment]
Yes that new dREL looks generally OK, how about a PR?

**Comment by vaitkus** [comment]
Great, thanks. I created the PR, just wanted to make sure first that the dREL is OK to avoid tweaking it in 6 different places.
