### ISSUE TITLE
cif_core.dic: description of the _atom_type_scat.versus_stol_list is misleading

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#216]
The current description of the `_atom_type_scat.versus_stol_list` data item is as follows:
```
    List of scattering factors as a function of sin theta on lambda.
    List has the form [[<stol value 1> <scatfac 1>] [<stol value 2> <scatfac 2>] ....]
    in increments of 0.01, increasing from 0.0.
```
However,  after changes made in commit 0bc98b3 the described form of `[[<stol value 1> <scatfac 1>] [<stol value 2> <scatfac 2>] ... ]` does not match the rest of the definition that defines the value as a non-nested array of real numbers:
```
    _type.container               Array
    _type.dimension               '[]'
    _type.contents                Real
```

**Comment by jamesrhester** [comment]
It appears this list is not used or calculated anywhere. I believe the `[]` notation is intended to say that there are no dimensional constraints expressible in the `_type.dimension` notation, as we don't have a previously proposed `*` notation available so that we could say `[2,*]` to mean an arbitrary-length list of 2-item lists. What we should really do is either remove this data name altogether, potentially replacing it with a straightforward category that presents this information in a loop, or else introduce "*" as a dimension. I am in favour of the former as it is the proper way to present information in a relational context. As it is not used at present we could easily replace it with a subcategory like `_atom_type_scat_table.{pt_id,symbol, stol, factor}` where I have deliberately introduced an opaque identifier to avoid real number `stol` becoming part of a key. Of course the joy of the list is that it can be guaranteed to be ordered, unlike a loop. So the use of a list is purely for optimisation purposes. Any thoughts?

**Comment by vaitkus** [comment]
I also prefer the new category approach since it does not require changes to the DDLm reference dictionary. As for the ordering of the data points, an additional data item (i.e. `_atom_type_scat_table.pt_index`) could be introduced to record the position of the point for the given atom type (making the natural key [symbol, index]).

However, I would rather deprecate the `_atom_type_scat.versus_stol_list` data item instead of outright removing it since it is also defined in the DDL1 `CIF_CORE` dictionary. Furthermore, if we do decide to retain the `_atom_type_scat.versus_stol_list` data item, it might be a good idea to change the data type, container, etc. values to the ones used in the DDL1 dictionary (that is, change it to a simple character string) prior to deprecation. This would greatly improve the compatibility between DDL1 and DDLm dictionaries as currently this is one of the two data items [1] that cannot be made compliant both to DDL1 and DDLm versions of the `CIF_CORE` dictionary due to the mandatory list container that is not supported by DDL1/CIF 1.1.

[1] The other item being `_exptl_crystal.colour` (see #189).

**Comment by jamesrhester** [comment]
Agreed. I will prepare a pull request that reverts `_atom_type_scat` to the DDL1 equivalent and defines a new category `_atom_type_scat_table` which presents the same information in relational fashion. `_atom_type_scat_table.pt_index` is not necessary as the optimisation is just that the points appear already ordered in the list. If they do appear unordered, it is just as easy to sort on `stol` as on `pt_index`. Also, for the record, `_atom_type_scat_table` should not be a sub category of `_atom_type_scat` as the keys are different.
