### ISSUE TITLE
`DIFFRN_STANDARDS` category in DDL1 changed to `DIFFRN_STANDARD` in DDLm

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/cif_core#291]
Although now essentially a historical relic, I noticed that the `_diffrn_standards_*` data names in DDL1 have been transformed into `_diffrn_standard.*` data names in DDLm, i.e. the `s` has been dropped. This breaks the convenient heuristic that valid DDL1 data names can be created by simply replacing the `.` with `_` in DDLm. I can see no useful reason for this change and suggest simply reverting to the `_diffrn_standard.*` form as the "new" form will never have been used (and the old form almost never was either I would guess).

One reason may be that `DIFFRN_STANDARD_REFLN`, which is a notional child of `DIFFRN_STANDARD`, does not have the `S`, but this is not a formal naming requirement and has no formal semantic implications.

If there are no objections I will prepare a pull request, as I don't think this is controversial or even significant.

**Comment by jamesrhester** [comment]
I should add that the dotted data name version with the `S` is listed as an alias, so the straight `_` -> `.` transformation does produce a valid data name.

**Comment by vaitkus** [comment]
I do not have any objections to the proposed changes.

However, I think that the heuristic ("_valid DDL1 data names can be created by simply replacing the `.` with `_` in DDLm_") should not be relied on or recommended in its current form (not sure if it is written down in any official sources). It seems that more than 40 data items in the `CIF_CORE` dictionary do not satisfy this criteria, even though the items are defined both in DDL1 and DDLm (see table below for more details). This excludes any data items that were marked as replaced in DDL1 (e.g. `_symmetry_Int_Tables_number`) since it makes sense to only include them as aliases. 

| DDLm name  | DDL1 name |
| ------------- | ------------- |
| `_atom_sites_Cartn_transform.mat_*`  |  `_atom_sites_Cartn_tran_matrix_*`  |
| `_atom_sites_Cartn_transform.vec_*` | `_atom_sites_Cartn_tran_vector_*` |
| `_atom_sites_fract_transform.mat_*` | `_atom_sites_fract_tran_matrix_*` |
| `_atom_sites_fract_transform.vec_*` | `_atom_sites_fract_tran_vector_*` |
| `_atom_type.analytical_mass_percent` | `_atom_type_analytical_mass_%` |
| `_computing.diffrn_collection` | `_computing_data_collection` |
| `_computing.diffrn_reduction` | `_computing_data_reduction` |
| `_diffrn_detector.description` | `_diffrn_detector` |
| `_diffrn_detector.make` | `_diffrn_detector_type` |
| `_diffrn_measurement.device_class` | `_diffrn_measurement_device` |
| `_diffrn_measurement.device_make` | `_diffrn_measurement_device_type` |
| `_diffrn_radiation_wavelength.value` | `_diffrn_radiation_wavelength` |
| `_diffrn_refln.intensity_net_su`  | `_diffrn_refln_intensity_u` |
| `_diffrn_refln.sin_theta_over_lambda` | `_diffrn_refln_sint/lambda` |
| `_diffrn_reflns.point_measured_fraction_full` | `_diffrn_reflns_point_group_measured_fraction_full` |
| `_diffrn_reflns.point_measured_fraction_max` | `_diffrn_reflns_point_group_measured_fraction_max` |
| `_diffrn_source.take_off_angle` | `_diffrn_source_take-off_angle` |
| `_diffrn_source_make` | `_diffrn_source_type` |
| `_diffrn_standard.decay_percent` | `_diffrn_standards_decay_%` |
| `_diffrn_standard.scale_su_average` | `_diffrn_standards_scale_u` |
| `_geom_angle.value` | `_geom_angle` |
| `_geom_torsion.value` | `_geom_torsion` |
| `_refine_ls.shift_over_su_max` | `_refine_ls_shift/su_max` | 
| `_refine_ls.shift_over_su_max_lt` | `_refine_ls_shift/su_max_lt` |
| `_refine_ls.shift_over_su_mean` | `_refine_ls_shift/su_mean` |
| `_refine_ls.shift_over_su_mean_lt` | `_refine_ls_shift/su_mean_lt` |
| `_refln.F_meas_su` | `_refln_F_sigma` |
| `_refln.F_squared_meas_su` | `_refln_F_squared_sigma` |
| `_refln.intensity_meas_su` | `_refln_intensity_sigma` |
| `_refln.sin_theta_over_lambda` | `_refln_sint/lambda` |
| `_reflns_shell.meanI_over_suI_all` | `_reflns_shell_meanI_over_uI_all` |
| `_reflns_shell.meanI_over_suI_gt` | `_reflns_shell_meanI_over_uI_gt` |

This showcases several problems with the heuristic:
* Some DDL1 data names cannot be properly expressed in a dotted DDLm form since they match their category name (e.g. `_geom_angle`).
* Some DDL1 data names clash with the DDLm SU item naming convention (e.g. `_diffrn_refln.intensity_net_su` vs. `_diffrn_refln_intensity_u`).
* Although not included in the table, there are multiple DDLm data items that are simply not present in the DDL1 version (Id items, SU items, data items with complex data structures).

Also, please note that renaming `DIFFRN_STANDARD` to `DIFFRN_STANDARDS` will not make the heuristic applicable to all items from this category (e.g. `_diffrn_standard.decay_percent` vs. `_diffrn_standards_decay_%`).

We have been applying a slightly different heuristic, however, which can be summarised as: _dot symbols (`.`) in DDLm data names can be replaced by underscores (`_`) without changing the meaning of the data name._ This holds true for most data items that were ported from from DDL1 (underscored versions are included as aliases), however, it fails for data items from the DDL2 symmetry dictionary and some of the newly added items (e.g. `_diffrn_measurement.specimen_attachment_type`).  This heuristic simplifies some of the coding tasks, but is it something that is actually supported by the IUCr? Would it be worthwhile to explicitly record it in the DDLm stye guide and add appropriate GitHub actions checks? If yes, I can open a separate issue for the discussion.

**Comment by jamesrhester** [comment]
Thank you for the comprehensive table. I agree that the heuristic as I expressed it was incorrect, and I think it is unnecessary to start renaming DDLm data names more globally as that undermines the perception that data names can be relied upon not to change. In the case of the `diffrn_standard` category I'm not so concerned as these are unused. Perhaps a better principle to justify my proposed renaming is that "DDLm categories should by default share the same name as their equivalent DDL1 and/or DDL2 category". In the present case I see no stylistic or semantic reason for introducing the divergence from this rule.

Regarding  _dot symbols (`.`) in DDLm data names can be replaced by underscores (`_`) without changing the meaning of the data name._ :  As I recall, the original idea was that, when searching for a legacy equivalent for a DDLm data name, it would be acceptable to try out this substitution: if this resulted in a recognisable data name, then you could be sure that it had the same meaning. In other words, we can guarantee that no all-underscore data name would ever be defined with a different meaning. It should not be taken as expecting an equivalent all-underscore style name will always be defined or should always be recognised - the only source of truth on the existence of a data name is the dictionary.

The point of that suggestion as I remember it was to help legacy software authors dealing with dotted data names: for many simple, common use cases (like cell parameters, space group, atomic positions) performing the substitution would yield an all-underscore name that the legacy software understood.

There is an as-yet not updated chapter in Volume G giving advice on how to go about writing dictionaries and definitions - some principles for name construction would be included there. If anybody thinks it is worth documenting these principles, an issue in the `comcifs.github.io` repository would be the best place.

**Comment by vaitkus** [comment]
> Thank you for the comprehensive table. I agree that the heuristic as I expressed it was incorrect, and I think it is unnecessary to start renaming DDLm data names more globally as that undermines the perception that data names can be relied upon not to change. In the case of the `diffrn_standard` category I'm not so concerned as these are unused. Perhaps a better principle to justify my proposed renaming is that "DDLm categories should by default share the same name as their equivalent DDL1 and/or DDL2 category". In the present case I see no stylistic or semantic reason for introducing the divergence from this rule.

Thank you for the clarification. You are completely correct that the s-less items are not currently in use, at least as far as the COD is concerned. This can be quickly checked by inspecting the COD tag summary list [1]. It might be slightly out of date, but the general usage patterns are still very clear.

> Regarding dot symbols (.) in DDLm data names can be replaced by underscores (_) without changing the meaning of the data name. : As I recall, the original idea was that, when searching for a legacy equivalent for a DDLm data name, it would be acceptable to try out this substitution: if this resulted in a recognisable data name, then you could be sure that it had the same meaning. In other words, we can guarantee that no all-underscore data name would ever be defined with a different meaning. It should not be taken as expecting an equivalent all-underscore style name will always be defined or should always be recognised - the only source of truth on the existence of a data name is the dictionary.
>
> The point of that suggestion as I remember it was to help legacy software authors dealing with dotted data names: for many simple, common use cases (like cell parameters, space group, atomic positions) performing the substitution would yield an all-underscore name that the legacy software understood.

Ok, this heuristic is slightly stricter, but still very useful!

> There is an as-yet not updated chapter in Volume G giving advice on how to go about writing dictionaries and definitions - some principles for name construction would be included there. If anybody thinks it is worth documenting these principles, an issue in the comcifs.github.io repository would be the best place.

Ok, it would indeed be useful having this in writing.

[1] https://project-gemmi.github.io/pdb-stats/cod-tags.html

**Comment by jamesrhester** [comment]
That cod-tags link is fantastic! I'll raise an issue to create a data name creation guideline.
