### ISSUE TITLE
Does the `CELL` category really belong in `EXPTL`?

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/cif_core#294]
The `Set` category `EXPTL` is described as: 

> data items used to specify the experimental work
>     prior to diffraction measurements.

The `Set` `CELL` category is formally a child of `EXPTL`, suggesting that cells are derived before the experiment is run. While this was true in the early 90s when using point detectors, essentially all experiments now derive the cell from the diffraction images and so `CELL` belongs more clearly in the `DIFFRN` category. However, `CELL` has data names allowing the cell measurement temperature, pressure, and wavelength to be specified separately to those specified in `DIFFRN`.

Where multiple temperatures are used in an experiment, multiple cells will be determined as they will differ by temperature. Seen in this light, there is an implicit child data name of `_diffrn.id` in `CELL` which is only allowed to be skipped due to the `Set` nature of the `CELL` category. This further implies that `CELL` should be a child of `DIFFRN`, although it is true that the parent-child relationship of `Set` categories has no practical semantic implications.

So, assuming that we need to link `CELL` with `DIFFRN` in both a machine-readable and human-sensible manner, here are some steps to take:

1. Change the parent of `CELL` to `DIFFRN`

This has no noticeable effect on practical use but would improve consistency for very attentive human readers.

2. Add a child data name of `_diffrn.id` to `CELL` and child categories, including `CELL_MEASUREMENT`

This is a machine-readable way of stating that a particular cell relates to a particular set of diffraction conditions, and would be a sufficient basis for validation software to raise flags if values are different, without outright disallowing it.

3. Alias `_cell_measurement.{temperature/pressure/radiation}` to equivalent data names in `DIFFRN`

In combination with (2), this would make contradictory values semantically invalid. We would need to check a large corpus of all CIF files e.g. COD for conformance to see if this assumption holds.

4. Deprecate `_cell_measurement.{temperature/pressure/radiation}` in favour of the `DIFFRN` equivalents, or visa versa

This seems unlikely to make any difference as these data names are widely encoded into current reading and writing software.

My preference would be to do 1, 2 and 3, providing a COD check does not find any disagreements in existing files.

**Comment by vaitkus** [comment]
> The Set CELL category is formally a child of EXPTL, suggesting that cells are derived before the experiment is run. While this was true in the early 90s when using point detectors, essentially all experiments now derive the cell from the diffraction images and so CELL belongs more clearly in the DIFFRN category. However, CELL has data names allowing the cell measurement temperature, pressure, and wavelength to be specified separately to those specified in DIFFRN.

I agree that the definitions may need updating to reflect the modern times, however, CIF, as an archival file format, should retain the ability to properly describe older experiments (e.g. to provide differing cell and diffraction temperatures in separate data items).

> 3. Alias _cell_measurement.{temperature/pressure/radiation} to equivalent data names in DIFFRN
>
>In combination with (2), this would make contradictory values semantically invalid. We would need to check a large corpus of all CIF files e.g. COD for conformance to see if this assumption holds.

The proposed aliasing is very likely to produce a lot of semantically conflicting values. Luckily, cell/diffraction temperatures and pressures are recorded in the COD MariaDB SQL database and can thus can be easily compared by establishing a connection to the database (`mysql -u cod_reader -h www.crystallography.net cod`) and running queries of the following form:
```
SELECT `file`, `celltemp`, `diffrtemp`, `year` FROM `data` WHERE  abs(`celltemp` - `diffrtemp`) > 1 order by `year` DESC, `file` limit 20; 
```
The `celltemp` column is populated with values from the `_cell_measurement_temperature` data item while the `diffrtemp` column is populated from the `_diffrn_ambient_temperature` data item. I introduced the ">1" difference limit since very often the temperatures differ only very slightly (e.g. `273` vs. `273.15`) and I am not sure if this reflects the actual data or is just a manifestation of a  bug/feature of the refinement program that was used. Even with this cut-off there are over 450 structures that have been published later than 2015 and have differing diffraction and cell temperatures. Hope this helps.

A similar test can be carried out for the pressure using the `cellpressure`  (based on `_cell_measurement_pressure`) and `diffrpressure` (based on `_diffrn_ambient_pressure`) columns. Cell radiation information is not readily available, but hopefully temperature and pressure is enough to aid in decision making.

**Comment by jamesrhester** [comment]
Thanks for the pointer to the sql interface to COD. I also wrote a little routine to compare arbitrary tags in a local copy of COD and had discovered that around 1% have noticeably different values for the two temperatures. Can anybody explain what that might mean, given that the atomic distances depend on the cell parameters? Surely if the cell and diffrn temperatures are markedly different, then it is impossible to determine the atomic distances?

**Comment by jamesrhester** [comment]
[I've consulted with the core CIF group](https://www.iucr.org/__data/iucr/lists/coredmg/msg00421.html), and two developers agree that these numbers should be the same. Indeed, a CheckCIF level A (most serious) alert is produced if they do not match. It also seems that SHELX created a default value for the `_cell_measurement_temperature` that was RT, and so sometimes this could have flowed through to the output file.

Moving forward, I agree with @vaitkus that we do need to retain the archival option of specifying a cell measurement temperature that is different for those situations where the cell measurement and diffraction measurement are separate.

We should also consider mmCIF, which shares these data names. In mmCIF, `CELL` and `CELL_MEASUREMENT` are simply classed as categories that describe the unit cell, and they are keyed to `_entry.id`, i.e. the ID for the whole data block. There is no stipulation as to when the cell was determined and given the age of the PDB some of the entries will relate to point detector data i.e. the cell might have been measured separately from data collection.

Thus we are forced to accept that items in `CELL_MEASUREMENT` may relate to the diffraction pattern, or to separate measurements.

So I propose the following simple resolution:

1. Categories `CELL`/`CELL_MEASUREMENT(_REFLN)` are shifted to `DIFFRN` (no tangible consequences, but the implication is that all are collected under the same conditions).
2. Category `CELL_MEASUREMENT` definitions are clarified to emphasise that the temp/pressure items relate only to measurements performed separately to the diffraction experiment.

This is more or less (1) and (2) from the original issue, and the default value for the `CELL_MEASUREMENT` temp/pressure items would be expressed using dREL to be the same as the `_diffrn` temp/pressure items.

Sound good?

**Comment by vaitkus** [comment]
@jamesrhester, did PR #358 fully resolve this issue? Should it be closed?

**Comment by jamesrhester** [comment]
Yes.
