### ISSUE TITLE
"photons per second" - unit with no underscores?

### ISSUE THREAD

**Issue by rowlesmr** [COMCIFS/cif_core#303]
I just noticed that there is a unit defined as [`'photons per second'`](https://github.com/COMCIFS/cif_core/blob/6673ac0da6f8413ce9320133d19f4b14bf7ffd0c/templ_enum.cif#L847), with spaces instead of underscores, as all other units have.

Is this intentional?

Matthew

**Comment by vaitkus** [comment]
I agree that the syntax of this data item looks a bit out of place, but it was purposely introduced in this form to retain compatibility with the `imgCIF` dictionary (see the discussion in PR #296 for more details).

I have also raised an issue with a suggestion to rename these units in the  `imgCIF` repository (https://github.com/yayahjb/cbflib/issues/40), but I have not yet received a response. Once (and if) the unit is renamed in `imgCIF`, the same will be done in the DDLm reference dictionary.

**Comment by rowlesmr** [comment]
No worries. Thanks for the response.

**Comment by vaitkus** [comment]
I would actually leave this issue open until it is resolved (or the `imgCIF` people reply with a negative response).

**Comment by vaitkus** [comment]
This issue seems to be slightly more serious than initially thought. The "photons per second" unit is not compatible with the content type of the `_units.code` attribute that lists it as one of the allowed enumeration values (the `Code` type does not allow spaces). There was some additional communication with the maintainers of the `imgCIF` dictionary via email, and they are quite willing to rename the units to the underscore variant if no objections are raised in about two weeks time.

Alternatively, we could change the content type of the `_units.code` attribute, but currently there does not seem to be a suitable alternative type that would both allow spaces and be case insensitive.

**Comment by vaitkus** [comment]
The `imgCIF` dictionary has now been split into a new separate repository [1]. The latest draft version of the dictionary in that repository (version 1.8.8) has replaced the `photons per second` unit with `photons per second`.

PR #472 makes a corresponding change in the DDLm reference dictionary, however, we might want to delay the merging of this PR the proper release of `imgCIF` dictionary version 1.8.8 just to be safe. (Although further change to the name of these units is highly unlikely). 

[1] https://github.com/yayahjb/cbf_imgcif_dictionary/tree/main
