### ISSUE TITLE
temp_enum.cif: potentially missing negative exponent in the desciptions of some units of measure

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#308]
The `units_code` save frame defines units of measure used in multiple CIF dictionaries.

Some of the descriptions seems to have an internal structure of some sorts, although, I was am not aware of an exact specification for it. The description usually takes the form of:
```
"general_unit_class 'human readable description (mathematical expression)'"
```
For example:
```
"length    'metres (metres * 10^(0))'"
```
Not sure if this is really a mistake, but I noticed that units of electron density seem to be missing the negative exponent in their mathematical expressions:
https://github.com/COMCIFS/cif_core/blob/1191d5f88030b38bf6bcc1028dcae6cb3f0ccf8f/templ_enum.cif#L824-L829

That is,
```
"electron-density 'electrons per angstroms  cubed (metres * 10^(-10))^3'" 
```
should actually be
```
"electron-density 'electrons per angstroms  cubed (metres * 10^(-10))^-3)'" 
```
Here I assume that electrons are unitless and that the mathematical expression applies to the entire unit and not only to the "angstroms cubed" part.

**Comment by jamesrhester** [comment]
As far as I know there is no standard for the way this section is parsed, but it looks like the options were being kept open for dimensionality calculations being possible. I think we might as well try to be consistent. If `electrons` are a unit then would it make sense to write these e.g. `electrons * (metres * 10^( -9)^(-3))' ?

As there is no defined standard here (strictly speaking these are just human-readable text strings) we are free to explore options that would make automated dimensionality calculations possible, but the proper way to do that would be to use DDLm attributes and dREL rather than embed information in text strings. At the moment I don't think this is a priority.
