### ISSUE TITLE
11 coefficient scattering factors? Cromer-Mann vs Waasmaier & Kirfel

### ISSUE THREAD

**Issue by rowlesmr** [COMCIFS/cif_core#357]
Are there any particular reasons that the 11-coefficient scattering factors [1] aren't included in core?

[1]    D. Waasmaier & A. Kirfel, New Analytical Scattering Factor Functions for Free Atoms and Ions for Free Atoms and Ions, Acta Cryst. (1995). A51, 416-413

**Comment by rowlesmr** [comment]
There is no way to include an arbitrary sum of gaussian approximation to the scattering factors. 

The two set of tags (`_atom_type_scat.cromer_mann_*` and `_atom_type_scat.hi_ang_fox_*`) assume you have four gaussians and a constant or three whatever-the-fox-one-is coefficients, respectfully. The tags assume International Tables for Crystallography, Vol. C (1991) Tables 6.1.1.4 and 6.1.1.5, and are therefore, redundant.

This makes it impossible to record alternate (gaussian) parameterisations of scattering factors.

**Comment by jamesrhester** [comment]
There is no particular reason that the others haven't been included. The reason for including analytical scattering factor functions at all in the dictionary is so that a structure factor can be calculated according to the dREL equations in the dictionary. There is absolutely no barrier to defining analogous coefficients, e.g. `_atom_type_scat.Waasmaier_Kirfel` or, if we can generalise, defining `_atom_type_scat.Gaussian_coeff` which takes a `List` and is therefore of any length (like we did in the powder dictionary for background). The tables in `templ_enum.cif` would then have a list of numbers for each atom type and we would change the dREL for `_refln.form_factor_table` to access `_atom_type_scat.Gaussian_coeff`.
