### ISSUE TITLE
Introduce a default value to the `_citation.id` data item

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#363]
During the discussion in https://github.com/COMCIFS/cif_core/issues/58 it was decided to remove almost all default enumeration values due to them being potentially misleading. However, defaults related to `PUBL` were left untouched on the basis that they do not relate to data as much (hopefully the same logic extends to the  `_citation.id` data item).

The  `_citation.id` data item serves as a primary key of the `CITATION` category. However, due to legacy reasons the item is assigned the `Encode` purpose rather than the `Key` purpose which is assigned to keys with arbitrary values. Specifically, the `Encode` purpose is needed since `_citation.id`  has one special value `primary` which indicates that the citation is the primary one. As a result, during the validation process the missing `_citation.id`  data item is reported even if there is only a single packet in the `CITATION` loop (a very common occurrence), since the value cannot be automatically elided.

I propose to resolve this issue by introducing `primary` as the default. This will work well with loops that only have a single entry (which is most likely the primary) and the validation will still properly detect the missing key in cases when there is more than one loop since the default key will not be unique.

**Comment by jamesrhester** [comment]
I think the logic you describe is precisely implemented by a dREL method that sets `_enumeration.default` to `primary` if there is one packet in the loop, and otherwise leaves it as `missing`. The reason I think directly setting `_enumeration.default` to `primary` would be wrong is that this is not a generally true statement, and is ultimately allowing contradictory information about an item: yes it is a key, but yes all of its values could be `primary`.
