### ISSUE TITLE
cif_core.dic: some default enumeration values are given in DDLm, but not in DDL1

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#58]
When compared to the ``DDL1`` version of the dictionary the ``DDLm`` seems to contain multiple additional enumeration values. For the sake of readability they will be divided into arbitrary categories in this issue report:

**1. Experimental**

| ID  | Data name  | Default | 
|---|---|---|
| 1.1 | _exptl_crystal_density_meas_temp | 293.  |
| 1.2 | _exptl_crystal_density_meas_temp_lt  | 293. |
| 1.3 | _exptl_crystal_density_meas_temp_gt | 293. |
| 1.4 |  _exptl_crystals_number | 1 |
| 1.5 |  _exptl_absorpt_correction_type | none |
| 1.6 |  _exptl_crystal_colour_primary | white |

The _exptl_crystals_number and _exptl_absorpt_correction_type seem reasonable, but should
exptl_crystal_density_meas_temp\_* and_exptl_crystal_colour_primary have default values at all?

**2. Atom sites solution**

| ID  | Data name  | Default | 
|---|---|---|
| 2.1 |  _atom_sites_solution_hydrogens | difmap |
| 2.2 |  _atom_sites_solution_primary | direct |
| 2.3 |  _atom_sites_solution_secondary | difmap |

**3. Diffraction radiation**

| ID  | Data name  | Default | 
|---|---|---|
| 3.1 | _diffrn_radiation_wavelength_determination | fundamental |
| 3.2 | _diffrn_radiation_probe | x-ray |
| 3.3 | _diffrn_radiation_xray_symbol | K-L\~3\~ |
| 2.4 | _diffrn_radiation_source | tube |
| 3.5 |  _diffrn_source_target | Cu |

Note: the `_diffrn_radiation_source` data item has only become an enumerator value in the DDLm version of the dictionary. It is more thoroughly discussed in issue #59.

**4. Reflections**

| ID  | Data name  | Default | 
|---|---|---|
| 4.1 | _refln\_[A\|B\|F\|F_squared]_calc | 0 |
| 4.2 | _refln\_[A\|B\|F\|F_squared]_meas | 0 |
| 4.3 | _refln\_[F\|F_squared]_sigma | 0 |

**5.Diffraction reflections**

| ID  | Data name  | Default | 
|---|---|---|
| 5.1 | _diffrn_refln_scan_mode | ot |
| 5.2 | _diffrn_refln_scan_mode_backgd | st |

**6.Chemical**

| ID  | Data name  | Default | 
|---|---|---|
| 6.1 | _chemical_enantioexcess_crystal_technique | CD |
| 6.2 | _chemical_enantioexcess_bulk_technique | OA |
| 6.3 | _chemical_absolute_configuration | . |

**7.Refinement**

| ID  | Data name  | Default | 
|---|---|---|
| 7.1 | _atom_site_refinement_flags | . |
| 7.2 | _atom_site_refinement_flags_adp | . |
| 7.3 | _atom_site_refinement_flags_posn | . |
| 7.4 | _atom_site_refinement_flags_occupancy | . |

Seems reasonable since the lack of these data items imply that the related techniques were not applied thus resulting in a '.' (inapplicable) special value.

**8.ADP**

| ID  | Data name  | Default | 
|---|---|---|
| 8.1 | _atom_site_adp_type | Uiso |

Seems reasonable.

**9.Crystal system**

| ID  | Data name  | Default | 
|---|---|---|
| 9.1 | _space_group_crystal_system | triclinic |

This addition seems a bit strange. Might it be related to the removal of the default _cell_angle_* values (discussed in #57)?

**10.Bibliography**

| ID  | Data name  | Default | 
|---|---|---|
| 10.1 | _journal_page_first | 1 |
| 10.2 | _publ_body_element | section |
| 10.3 | _journal_index_type | O |
| 10.4 |  _citation_coordinate_linkage | yes |

The _journal_page_first default value does not seem reasonable since e-journals might not have page numbers at all in some instances. I would suggest not assigning a default value.

**11. Symops**

| ID  | Data name  | Default | 
|---|---|---|
| 11.1 | _geom_angle_site_symmetry\_[1\|2\|3] | 1_555  |
| 11.2 | _geom_bond_site_symmetry\_[1\|2] | 1_555 |
| 11.3 | _geom_contact_site_symmetry\_[1\|2] | 1_555 |
| 11.4 | _geom_hbond_site_symmetry\_[A\|D\|H] | 1_555 |
| 11.5 | _geom_torsion_site_symmetry\_[1\|2\|3\|4] | 1_555 |

These values seem reasonable.

**12. Various vectors and matrices**

| ID  | Data name  | Default | 
|---|---|---|
| 11.1 | _atom_site_aniso_B\_[*] | ?  |
| 11.2 | _atom_site_aniso_U\_[*] | ?  |
| 11.3 |_atom_sites_Cartn_tran_matrix\_[*] | ?  |
| 11.4 | _atom_sites_Cartn_tran_vector\_[*] | ?  |
| 11.5 | _atom_sites_fract_tran_matrix\_[*] | ? |
| 11.6 | _atom_sites_fract_tran_vector\_[*] | ? |
| 11.7 | _diffrn_orient_matrix_UB\_[*] | ? |
| 11.8 | _diffrn_reflns_transf_matrix\_[*] | ? |

Does having a '?' default value convey any meaning? Also, since this default value is imported from the 'templ_atrr.cif' it would prevent the addition of a differing enumeration default for the importing data item if such need would ever arise.

Should all of these values be ported to DDL1 or did some of the were added unintentionally?

**Comment by jamesrhester** [comment]
Item 12: the '?' do not convey meaning and I will remove them from the DDLm core.
Item 11: I agree that these look reasonable
Item 1-10: I will ask the core dictionary maintenance group to consider these.

**Comment by jamesrhester** [comment]
The following comment is from David Brown:

These defaults should ABSLOLUTELY NOT appear in the dictionary. They were deliberately omitted from the original dictionaries because they are in no way guaranteed to be correct. Anyone looking for room temperature structures must know the difference between structures where the author states that the experiment was done at room temperature and those where the temperature was not given and might have had any value. It is impossible to do science properly if you are being fed information that you cannot rely on. An absorption correction may have been applied; the crystal has a high probability of not being white if the author fails to indicate the colour. There are many crystal structures reported without much of this information, and just because an author fails to say that he or she used Mo radiation does not mean they used copper. I did a study once on anisotropic atomic displacement parameters and had to reject most of the values reported in terms of B (rather than U or beta) because there are two conventions, and most authors did not say which convention they used. If I had been presented with an assumed default I would have had to reject all the results with the assumed value because I could not rely on its authenticity.

If default values are needed, they should be supplied by the application software that reads the CIF. Presumably it has a better idea of what the default should be as well as the effect of that such an assumption would have on the subsequent use of the information. The default value should always be ?, meaning that nothing is known about the value. Even the default . (period) would be wrong, since the dictionary cannot know whether an item is inapplicable or just not reported.

None of the suggestions in the list should be implemented. If something is unknown, it is, surprisingly, not known and should not be guessed at by a dictionary that knows nothing about the measurements, even if the dictionary gets it right much of the time.

**Comment by jamesrhester** [comment]
The conclusion is: none of these should be ported to DDL1 and all should be removed from DDLm.

**Comment by jamesrhester** [comment]
The latest update removes these from the DDLm dictionary. I have left the publ_ related ones as they do not relate to data as such.

**Comment by vaitkus** [comment]
I just wanted to note that some default enumeration values are still defined in the ``templ_attr.cif`` file that is imported by the core dictionary. These should probably be removed as well.

**Comment by jamesrhester** [comment]
These will be removed in the next update.

**Comment by vaitkus** [comment]
Thank You. Closing the issue since it has been resolved.
