### ISSUE TITLE
ddl.dic: is the presence of data items linked  by the _name.linked_item_id data item mandatory?

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#74]
The ``_name.linked_item_id`` data item defines a relation between two data items (usually as a primary/foreign key or value/su pair). However, it is not entirely clear if the presence of the data item, that is linked to, mandatory. It would seem logical to treat an *su* data item that does not have a corresponding *value* data item as a validation error, but does the same hold true for the primary/foreign key pairs?

For example, the ``_atom_site.type_symbol`` data item links to the ``_atom_type.symbol`` data item. Should a CIF file that contains only the ``_atom_site.type_symbol`` loop (and no ``_atom_type.symbol`` loop) be treated as valid or invalid according to the ``cif_core`` dictionary?

**Comment by jamesrhester** [comment]
The lack of a linked data name must be a violation, as this means semantically that there is no actual information on the properties of the item being referred to.

In a dREl context, the appearance of such a violation could trigger an attempt to calculate the missing items. For example, in cif_core, a category method exists to create the _atom_type category using the first component of the atom label.

It is also true that _atom_site.type_symbol could be used to create the _atom_type loop, but this is not done in the current dictionary.  I may rewrite the category method to allow this option.

**Comment by vaitkus** [comment]
Thank You for the clarification.

**Comment by jamesrhester** [comment]
I suggest that we make an exception to regarding this as a violation when the missing linked data name is the key of a parent category. in this case, the child category *is* providing some information about the item.

I once had a discussion with the architects of DDLm about this case, as in the legacy powder dictionary there are three categories that are best described as children of the `pd_data` category. However, there are no data names that are in the `pd_data` category itself, so strictly meeting the criterion that the linked data name should exist would mean that a `pd_data` loop should be constructed that contains only `_pd_data.id`. This is rather pointless as the contents of this category is just the union of all of the linked child category key data names.  So if we allow the exception above, such files will validate correctly.

**Comment by jamesrhester** [comment]
Sorry for leaving this for so long.

Philosophically the information about an atom type in the `_atom_type` table is vital to understanding the structure. However, because these identifiers are universal, leaving them out of a given data file is not usually an issue as the values can be looked up outside the CIF file. Indeed, the DDLm cif_core dictionary provides dREL methods and database values to automatically derive these missing values.

So I suggest that this is a matter for the particular validation philosophy: strictly speaking, the availability of a linked item remains mandatory. If the validator can determine unambiguous values for the missing linked item, then it may choose to downgrade or ignore missing linked items. Indeed, they are all derivable if you assume that anything in a child list will appear in a parent list.

You could have a 'strict' mode and a 'relaxed' mode for these circumstances.

**Comment by jamesrhester** [comment]
@vaitkus are you happy to close this issue?

**Comment by vaitkus** [comment]
Yes, thank you for the clarification.
