### ISSUE TITLE
Expand use of Citation category

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/cif_core#80]
The current definition of the citation category suggests that it is for listing the citations in a journal article. Some dictionaries may wish to simply list citations that are relevant to the object being described (see for example COMCIFS/TopoCif#13 ). Are there any objections to dropping the apparent restriction of citations listed in a data block to be those appearing in a publication corresponding to that data block?

**Comment by merkys** [comment]
I am a bit worried about the change of the meaning of this category. After expanding its use it will be impossible to tell which entries are the citations from the journal article, and which are relevant to the described object in some other way. The loss of the information could be prevented by, for example, introduction of data item ``_citation_source`` with possible values ``publication`` (i.e. originating from the journal article) and ``other``. What do you think?

**Comment by vaitkus** [comment]
I strongly support the suggestion to drop the restriction.

This restriction seems to originate in the ``DDLm`` version of the dictionary, since the ``DDL1`` dictionary states that:
```
Data items in the CITATION category record details about the
literature cited as being relevant to the contents of the data
block.
```
This older interpretation seems to correspond quite well to the potential needs of those other journals.

What is more, other databases seem to be already using the citation category as it was intended by ``DDL1``, i.e.: the ICSD includes the details of the original publication into the ``citation`` loop.

As for @merkys suggestion to differentiate between the citations the same can be achieved using the ``_citation.special_details`` data item, although, in a less specific way (free text field vs. enumerator).

**Comment by merkys** [comment]
I see. Therefore, to me it seems wiser to revert back to restriction-less DDL1 definition of ``_citation_*`` data items.

**Comment by jamesrhester** [comment]
I have returned the DDL1 wording to the core dictionary.
