### ISSUE TITLE
Provide reverse SU  link in _name.linked_item_id

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/cif_core#86]
The current DDLm specification provides for a data name that contains the standard uncertainty of another data name to flag this relationship by setting `_type.purpose` to `SU` and `_name.linked_item_id` to the data name that it holds the SU of.  However, it is more often useful to search in the opposite direction, that is, given a data name, find the data name that holds the SU. I therefore propose that, when a data name has `_type.purpose` of `Measurand`, a data name specified in `_name.linked_item_id` will hold the standard uncertainty.  The standard convention will still apply in DDLm dictionaries, that when an explicit specification is missing the SU is held in a data name that is the same as the Measurand data name with the characters `_su` added.

I note that DDL2 handles SU data names using the `item_related` series of attributes, by setting `_item_related.related_name` to the data name of the SU item, and `_item_related.function_code` to `associated_esd`.  In the DDL2 structure, multiple possible links can be specified. We may wish to consider a similar category in the future (e.g. `_name_related`).

**Comment by vaitkus** [comment]
I strongly support this proposal since it would make dictionary processing much easier. On the plus side, it would also prevent people from using measurand data items as primary loop keys.

The DDL2-like approach seems even better since it respects the principle that "the value of data item X should preferably not affect the interpretation of the Y data item value" which is somewhat ignored with the ``_type.purpose`` approach (both in the proposed change and the current handling of SU data items).

**Comment by jamesrhester** [comment]
I agree with your comments on the DDL2-style approach being more consistent with the general philosophy.

**Comment by jamesrhester** [comment]
Comment from Herbert Bernstein relayed from DDLm-group: 

> Before making this decision, we need to consider the general issue of requiring parents to accumulate all information on their children.  It makes the addition of new children more complex.  In general we could extract the information on parent-child relationships from either side.  We could require it on the parent, or on the child, or on both.  We should try to be consistent.

**Comment by jamesrhester** [comment]
In response to Herbert I have pointed out that data name - SU is a one-to-one link, rather than a one-to-many link. The latter is the usual context in which we talk about parent-child links, so I've suggested that his broader comment does not apply in this case.

**Comment by jcbollinger** [comment]
I have been thinking about this on and off for some time, and I have not been able to make myself comfortable with it.

First, I acknowledge that this is a somewhat different case than parent / child links.  In that case, the child will have `_type.purpose Link`, and that determines the relevant interpretation for that definition's linked_item_id.  Specifying an interpretation for a linked_item_id of Measurand items would not have inherent implications for Links or Keys.  Nevertheless, the same general issue does arise there: it is common to want to navigate from parent to child.  If we are going to denormalize DDLm in order to make navigation of some links more convenient, then it is unclear on what basis we would limit that to Measurand / SU links.

In the Measurement / SU case, moreover, DDLm *already* specifies how to find a Measurand item's SU item:

> This value must be accompanied by its standard uncertainty (SU) value, expressed either as:
>
> 1.   appended integers, in parentheses (), at the precision of the trailing digits, or
> 2.   a separately defined item with the same name as the measurand item but with an additional suffix '_su'. 

Note well that (2) is not merely a convention, it is a *rule*, expressed in the definition of `_type.purpose`.  Without lifting or loosening that, using a linked_item_id to point to the SU item would be doubly redundant: redundant with the association through item naming, and redundant with the **required** link coming from the other side.

If we did lift item (2), then my preference would still be to not implement this proposal.  I prefer to minimize redundancy, and in this case, the definition of the SU is the semantically correct place for the link to reside.  The definition of a Measurand is meaningful without a link to the associated SU, even though, taken by itself, that leaves some aspects of the interpretation of values of that item unclear.  On the other hand, the definition of an SU item is *not* meaningful without reference to the associated Measurand.  The SU needs to have the link in order for its definition to be complete.

Moreover, we have only one link to work with per item, at least at present, and using Measurands' links for this purpose will foreclose using them for any other purpose in the future.  For example, although it is not a practice endorsed by COMCIFS for dictionaries it manages, if we wanted to support associating measurements with measurement units on a per-value basis, then this would be a more natural use for Measurands' links.

I do appreciate that programs generally want to traverse the existing SU -> Measurand link in the reverse direction.  If the idea is to simplify doing that in methods then I would be open to defining a dREL function for that purpose.  In more general programming context, however, I think the programmatic advantage available from implementing this proposal is small, given that programs that use dictionaries to interpret CIF data need to parse and use dictionaries as a whole, anyway.  Thus, as a practical matter, whatever information could be written into measurands' own definitions to link them to su items can be filled in almost as easily and with less opportunity for inconsistency when the relevant SU items' definitions are processed.

I would also be open to considering moving item links to a new category, thereby affording the possibilities of multiple links per item and of labeling links with specific purposes, as in DDL2.  I note, however, that that would not in any way simplify the programmatic link traversal situation presented as the impetus for this proposal.

**Comment by jamesrhester** [comment]
On reflection I think that I agree with @jcbollinger that this problem can equally well be solved within software by collecting reverse links as they are encountered.  I would like to reserve discussion of creating a DDL2-like link category until a decent use-case appears.
