### ISSUE TITLE
ddl.dic: explicitly state if imports of the 'Head' category are allowed in non-head context

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/cif_core#88]
Currently, the description of ``_import.details_mode`` states that
```
As a special case, a 'Head' category importing a 'Head' category is
equivalent to importing all children of the imported 'Head' category
as children of the importing 'Head' category.
```
However, from this definition it is not entirely clear how an import
of a 'Head' category into a non-'Head' category should be treated
and if it is at all allowed.

A clarification on this topic would be useful.

**Comment by jamesrhester** [comment]
I see the issue: importing a 'Head' category into a non-'Head' category causes semantic problems, because then a definition with `_definition.class` of 'Head' is not the actual 'Head'.  I think we should state that this is another special case: `_definition.class` should become `Set` in this case.  We could also just not allow it, but that would not permit grafting of whole dictionaries into some sort of larger tree structure. We are not planning to create such definition trees, but they sound vaguely useful.

**Comment by vaitkus** [comment]
I would propose restricting such imports for now until the actual need arises. Loosening these restrictions would only constitute a minor dictionary change while restricting it once permitted would constitute a major change.

 However, either way is fine as long as it is properly document.

**Comment by jamesrhester** [comment]
Have edited the description to explicitly forbid importing Head categories into non-Head categories. Will be in the next commit.

**Comment by vaitkus** [comment]
Great, thank You.

Closing.
